%%% Code generated by scripts/generate-protocols
%% @doc IRecord 协议
%% @desc
%% - 功能：标识协议，用于标记记录类型
%% - 说明：作为标记接口使用，用于识别 Clojure 中的记录（record）类型
-module('clojerl.IRecord').

-include("clojerl.hrl").
-include("clojerl_int.hrl").

-clojure(true).
-protocol(true).

-export([?SATISFIES/1]).
-export([?EXTENDS/1]).

-callback '_IRecord'(any()) -> any().
-optional_callbacks(['_IRecord'/1]).

-export_type([type/0]).
-type type() :: #{_ => _}.

?SATISFIES(X) ->
  case X of
    #{?TYPE := _} ->  false;
    X_ when erlang:is_binary(X_) ->  false;
    X_ when erlang:is_boolean(X_) ->  false;
    ?NIL ->  false;
    _ -> false
  end.

?EXTENDS(X) ->
  case X of
    _ -> false
  end.
