%%% Code generated by scripts/generate-protocols
%% @doc 向量协议
%% @desc
%% - 功能：定义向量数据结构的接口，提供基于索引的随机访问能力
%% - 依赖：被 Subvec 和 Vector 实现
-module('clojerl.IVector').

-include("clojerl.hrl").
-include("clojerl_int.hrl").

-clojure(true).
-protocol(true).

-export([?SATISFIES/1]).
-export([?EXTENDS/1]).

-callback '_IVector'(any()) -> any().
-optional_callbacks(['_IVector'/1]).

-export_type([type/0]).
-type type() :: #{_ => _}.

?SATISFIES(X) ->
  case X of
    #{?TYPE := 'clojerl.Subvec'} ->  true;
    #{?TYPE := 'clojerl.Vector'} ->  true;
    #{?TYPE := _} ->  false;
    X_ when erlang:is_binary(X_) ->  false;
    X_ when erlang:is_boolean(X_) ->  false;
    ?NIL ->  false;
    _ -> false
  end.

?EXTENDS(X) ->
  case X of
    'clojerl.Subvec' -> true;
    'clojerl.Vector' -> true;
    _ -> false
  end.
