%%% Code generated by scripts/generate-protocols
%% @doc IPending 协议
%% @desc
%% - 功能：用于表示延迟计算或尚未完成计算的对象
%% - 说明：定义了检查对象是否已经实现（realized）的方法，适用于 Delay、Future、Promise 等类型
-module('clojerl.IPending').

-include("clojerl.hrl").
-include("clojerl_int.hrl").

-clojure(true).
-protocol(true).

-export(['realized?'/1]).
-export([?SATISFIES/1]).
-export([?EXTENDS/1]).

-callback 'realized?'(any()) -> any().
-optional_callbacks(['realized?'/1]).

-export_type([type/0]).
-type type() :: #{_ => _}.

'realized?'(X) ->
  case X of
    #{?TYPE := 'clojerl.Delay'} ->
      'clojerl.Delay':'realized?'(X);
    #{?TYPE := 'clojerl.Future'} ->
      'clojerl.Future':'realized?'(X);
    #{?TYPE := 'clojerl.Promise'} ->
      'clojerl.Promise':'realized?'(X);
    #{?TYPE := _} ->
      clj_protocol:not_implemented(?MODULE, 'realized?', X);
    X_ when erlang:is_binary(X_) ->
      clj_protocol:not_implemented(?MODULE, 'realized?', X);
    X_ when erlang:is_boolean(X_) ->
      clj_protocol:not_implemented(?MODULE, 'realized?', X);
    ?NIL ->
      clj_protocol:not_implemented(?MODULE, 'realized?', X);
    _ ->
      clj_protocol:not_implemented(?MODULE, 'realized?', X)
  end.

?SATISFIES(X) ->
  case X of
    #{?TYPE := 'clojerl.Delay'} ->  true;
    #{?TYPE := 'clojerl.Future'} ->  true;
    #{?TYPE := 'clojerl.Promise'} ->  true;
    #{?TYPE := _} ->  false;
    X_ when erlang:is_binary(X_) ->  false;
    X_ when erlang:is_boolean(X_) ->  false;
    ?NIL ->  false;
    _ -> false
  end.

?EXTENDS(X) ->
  case X of
    'clojerl.Delay' -> true;
    'clojerl.Future' -> true;
    'clojerl.Promise' -> true;
    _ -> false
  end.
