%%% Code generated by scripts/generate-protocols
%% @doc 类型协议
%% @desc
%% - 功能：定义类型系统的基础协议，用于类型检查和类型相关操作
%% - 依赖：作为基础协议，被其他协议和类型系统引用
-module('clojerl.IType').

-include("clojerl.hrl").
-include("clojerl_int.hrl").

-clojure(true).
-protocol(true).

-export([?SATISFIES/1]).
-export([?EXTENDS/1]).

-callback '_IType'(any()) -> any().
-optional_callbacks(['_IType'/1]).

-export_type([type/0]).
-type type() :: #{_ => _}.

?SATISFIES(X) ->
  case X of
    #{?TYPE := _} ->  false;
    X_ when erlang:is_binary(X_) ->  false;
    X_ when erlang:is_boolean(X_) ->  false;
    ?NIL ->  false;
    _ -> false
  end.

?EXTENDS(X) ->
  case X of
    _ -> false
  end.
