%%% Code generated by scripts/generate-protocols
%% @doc IExceptionInfo 异常信息协议
%% @desc
%% - 功能：定义携带额外数据的异常对象接口，用于获取异常的详细信息和原因
%% - 主要方法：
%%   - data/1: 获取异常携带的数据
%%   - cause/1: 获取导致此异常的原因
-module('clojerl.IExceptionInfo').

-include("clojerl.hrl").
-include("clojerl_int.hrl").

-clojure(true).
-protocol(true).

-export(['data'/1, 'cause'/1]).
-export([?SATISFIES/1]).
-export([?EXTENDS/1]).

-callback 'data'(any()) -> any().
-callback 'cause'(any()) -> any().
-optional_callbacks(['data'/1, 'cause'/1]).

-export_type([type/0]).
-type type() :: #{_ => _}.

'data'(ExInfo) ->
  case ExInfo of
    #{?TYPE := 'clojerl.ExceptionInfo'} ->
      'clojerl.ExceptionInfo':'data'(ExInfo);
    #{?TYPE := _} ->
      clj_protocol:not_implemented(?MODULE, 'data', ExInfo);
    X_ when erlang:is_binary(X_) ->
      clj_protocol:not_implemented(?MODULE, 'data', ExInfo);
    X_ when erlang:is_boolean(X_) ->
      clj_protocol:not_implemented(?MODULE, 'data', ExInfo);
    ?NIL ->
      clj_protocol:not_implemented(?MODULE, 'data', ExInfo);
    _ ->
      clj_protocol:not_implemented(?MODULE, 'data', ExInfo)
  end.

'cause'(ExInfo) ->
  case ExInfo of
    #{?TYPE := 'clojerl.ExceptionInfo'} ->
      'clojerl.ExceptionInfo':'cause'(ExInfo);
    #{?TYPE := _} ->
      clj_protocol:not_implemented(?MODULE, 'cause', ExInfo);
    X_ when erlang:is_binary(X_) ->
      clj_protocol:not_implemented(?MODULE, 'cause', ExInfo);
    X_ when erlang:is_boolean(X_) ->
      clj_protocol:not_implemented(?MODULE, 'cause', ExInfo);
    ?NIL ->
      clj_protocol:not_implemented(?MODULE, 'cause', ExInfo);
    _ ->
      clj_protocol:not_implemented(?MODULE, 'cause', ExInfo)
  end.

?SATISFIES(X) ->
  case X of
    #{?TYPE := 'clojerl.ExceptionInfo'} ->  true;
    #{?TYPE := _} ->  false;
    X_ when erlang:is_binary(X_) ->  false;
    X_ when erlang:is_boolean(X_) ->  false;
    ?NIL ->  false;
    _ -> false
  end.

?EXTENDS(X) ->
  case X of
    'clojerl.ExceptionInfo' -> true;
    _ -> false
  end.
